=== marcosrg9/LENMA/ejercicios/xml/ejercicios/consolas/consolas.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="consolas">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="consola" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="plataforma" type="xsd:string"/>
                            <xsd:element name="version" type="xsd:string"/>

                            <xsd:element name="juegos">
                                <xsd:complexType>
                                    <xsd:sequence>
                                    
                                    <xsd:element name="accion">
                                        <xsd:complexType>
                                            <xsd:sequence>
                                                <xsd:element name="nombre" maxOccurs="unbounded"/>
                                            </xsd:sequence>
                                        </xsd:complexType>
                                    </xsd:element>
                                    
                                    <xsd:element name="rol">
                                        <xsd:complexType>
                                            <xsd:sequence>
                                                <xsd:element name="nombre" maxOccurs="unbounded"/>
                                            </xsd:sequence>
                                        </xsd:complexType>
                                    </xsd:element>
                                    
                                    <xsd:element name="arcade">
                                        <xsd:complexType>
                                            <xsd:sequence>
                                                <xsd:element name="nombre" maxOccurs="unbounded"/>
                                            </xsd:sequence>
                                        </xsd:complexType>
                                    </xsd:element>
                                    

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                            <xsd:element name="fecLanzamiento" type="xsd:date"/>

                            <xsd:element name="exito">
                                <xsd:complexType>
                                    <xsd:sequence>

                                        <xsd:element name="ventas" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>

                                                    <xsd:element name="numero" type="xsd:integer"/>
                                                    <xsd:element name="mes" type="xsd:string"/>
                                                    <xsd:element name="anyo" type="xsd:integer"/>
            
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== marcosrg9/LENMA/ejercicios/xml/ejercicios/xsd/consolas/consolas.xml
<?xml version="1.0" encoding="UTF-8"?>

<consolas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="file:///Users/marcos/Desktop/LENMA/ejercicios/xml/ejercicios/consolas/consolas.xsd">

    <!-- PS4 -->
    <consola>
        <plataforma>PS</plataforma>
        <version>4</version>

        <juegos>
            <accion>
                <nombre>??</nombre>
            </accion>
            <rol>
                <nombre>??</nombre>
            </rol>
            <arcade>
                <nombre>??</nombre>
            </arcade>
        </juegos>

        <fecLanzamiento>2020-10-10</fecLanzamiento>

        <exito>
            <ventas>
                <numero>300</numero>
                <mes>ENERO</mes>
                <anyo>2022</anyo>
            </ventas>
            <ventas>
                <numero>100</numero>
                <mes>FEBRERO</mes>
                <anyo>2022</anyo>
            </ventas>
        </exito>
    </consola>

    <!-- PS5 -->
    <consola>
        <plataforma>PS</plataforma>
        <version>5</version>

        <juegos>
            <accion>
                <nombre>??</nombre>
            </accion>
            <rol>
                <nombre>??</nombre>
            </rol>
            <arcade>
                <nombre>??</nombre>
            </arcade>
        </juegos>

        <fecLanzamiento>2021-10-10</fecLanzamiento>

        <exito>
            <ventas>
                <numero>600</numero>
                <mes>ENERO</mes>
                <anyo>2022</anyo>
            </ventas>
            <ventas>
                <numero>300</numero>
                <mes>FEBRERO</mes>
                <anyo>2022</anyo>
            </ventas>
        </exito>
    </consola>

    <!-- XBOX -->
    <consola>
        <plataforma>XBOX</plataforma>
        <version>2020</version>

        <juegos>
            <accion>
                <nombre>??</nombre>
            </accion>
            <rol>
                <nombre>??</nombre>
            </rol>
            <arcade>
                <nombre>??</nombre>
            </arcade>
        </juegos>

        <fecLanzamiento>2019-10-10</fecLanzamiento>

        <exito>
            <ventas>
                <numero>1000</numero>
                <mes>ENERO</mes>
                <anyo>2022</anyo>
            </ventas>
            <ventas>
                <numero>800</numero>
                <mes>FEBRERO</mes>
                <anyo>2022</anyo>
            </ventas>
        </exito>
    </consola>
</consolas>
