=== marcosrg9/LENMA/ejercicios/xml/ejercicios/dtd/periodico/periodico.dtd
<!-- (FOO+) = Mínimo debe aparecer 1 vez -->
<!-- Puede ir dentro o fuera (símbolo) -->
<!ELEMENT NEWSPAPER (ARTICLE+)>
<!-- ()* = Elemento opcional -->
<!ELEMENT ARTICLE (HEADLINE, (BYLINE*), LEAD, BODY, NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>

<!-- 
    - Required -> requerido.
    - Implied  -> opcional.
    - fixed    -> valor fijo.
 -->
<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>

<!ENTITY NEWSPAPER "Vervet Logic Times">
<!ENTITY PUBLISHER "Vervet Logic Press">
<!ENTITY COPYRIGHT "Copyright 1998 Vervet Logic Press">

=== marcosrg9/LENMA/ejercicios/xml/ejercicios/dtd/periodico/periodico.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE NEWSPAPER SYSTEM "./periodico.dtd">

<NEWSPAPER>

    <ARTICLE AUTHOR="-">
        <HEADLINE>-</HEADLINE>
        <LEAD>-</LEAD>
        <BODY>-</BODY>
        <NOTES>-</NOTES>
    </ARTICLE>
    
    <ARTICLE AUTHOR="-">
        <HEADLINE>-</HEADLINE>
        <LEAD>-</LEAD>
        <BODY>-</BODY>
        <NOTES>&NEWSPAPER;</NOTES>
    </ARTICLE>

</NEWSPAPER>
