=== marcosrg9/LENMA/ejercicios/xml/ejercicios/dtd/futbol/futbol.dtd
<!ELEMENT futbol (equipos)>
    <!ELEMENT equipos (equipo)>
        <!ELEMENT equipo (nombreEquipo, copas, jugadores, equipacion, jugados, estadio)>
        
            <!ELEMENT nombreEquipo (#PCDATA)>
            <!ELEMENT copas (#PCDATA)>
            <!ELEMENT jugadores (pichichi)>
                <!ELEMENT pichichi (nombre, fechaNacimiento, goles, tarjetas)>
                    <!ELEMENT nombre (#PCDATA)>
                    <!ELEMENT fechaNacimiento (#PCDATA)>
                    <!ELEMENT goles (#PCDATA)>
                    <!ELEMENT tarjetas (amarillas, rojas)>
                        <!ELEMENT amarillas (#PCDATA)>
                        <!ELEMENT rojas (#PCDATA)>

            <!ELEMENT equipacion (primera, segunda)>
                <!ELEMENT primera (#PCDATA)>
                <!ELEMENT segunda (#PCDATA)>

            <!ELEMENT jugados (ganados, perdidos, empatados)>
                <!ELEMENT ganados (#PCDATA)>
                <!ELEMENT perdidos (#PCDATA)>
                <!ELEMENT empatados (#PCDATA)>

            <!ELEMENT estadio (nombreEstadio, capacidad)>
                <!ELEMENT nombreEstadio (#PCDATA)>
                <!ELEMENT capacidad (#PCDATA)>

=== marcosrg9/LENMA/ejercicios/xml/ejercicios/dtd/futbol/futbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol SYSTEM "file:///C:/Users/Usuario/Desktop/futbol.dtd">
<futbol>
    <equipos>
        <equipo>
            <nombreEquipo></nombreEquipo>
            <copas></copas>
            <jugadores>
                <pichichi>
                    <nombre></nombre>
                    <fechaNacimiento></fechaNacimiento>
                    <goles></goles>
                    <tarjetas>
                        <amarillas></amarillas>
                        <rojas></rojas>
                    </tarjetas>
                </pichichi>
            </jugadores>
            <equipacion>
                <primera></primera>
                <segunda></segunda>
            </equipacion>
            <jugados>
                <ganados></ganados>
                <perdidos></perdidos>
                <empatados></empatados>
            </jugados>
            <estadio>
                <nombreEstadio></nombreEstadio>
                <capacidad></capacidad>
            </estadio>
        </equipo>
    </equipos>
</futbol>
